### ISSUE TITLE
not an issue but a question

### ISSUE THREAD

**Issue by EvanTeGreat** [Blobby-Boi/ExtHang3r#13]
when i hang the extension, how do i turn it back on, also my admin has two extensions: GoGuardian and Cisco umbrella. Hanging the cisco umbrella does not work

**Comment by goguardianbypass212** [comment]
type chrome://restart and when you want to turn it back off do the same steps as before.

**Comment by Blobby-Boi** [comment]
To turn it back on, close the exthang3r tab and flip the switch twice again.
