### ISSUE TITLE
Not an Issue But a new app Instead of sparkvue

### ISSUE THREAD

**Issue by jeffrey6576i** [Blobby-Boi/ExtHang3r#15]
Hello Blobby-boi there is an app called Vernier Spectral Analysis and its Kind of like Sparkvue or smth like that it can export files just like Sparkvue and open saved files like Sparkvue so I don't care if it takes you months to figure out this out just please save us all because sparkle got removed from the chrome web store and I accidentally deleted it and now I cant install it no more here's the link to Vernier Spectral Analysis https://chromewebstore.google.com/detail/vernier-spectral-analysis/neagmanoonoaijlnipjppnjknalpodmi 

Thank you for reading

By: Me ofc you noobs read my user.

**Comment by jeffrey6576i** [comment]
so that a yes or no

**Comment by Blobby-Boi** [comment]
its a "I will see what I can do"

**Comment by jeffrey6576i** [comment]
ok
